services:

  postgres:
    image: postgres:16
    container_name: postgres-produtos
    restart: always
    environment:
      POSTGRES_DB: bd-produtos
      POSTGRES_USER: coti
      POSTGRES_PASSWORD: coti
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-produtos
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: coti@email.com
      PGADMIN_DEFAULT_PASSWORD: Coti@2026
    ports:
      - "5051:80"
    depends_on:
      - postgres

volumes:
  postgres_data: